### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [huykirbyLL/walter-s-masterman_the-wrong-letter#2]
# General Issues:

- [x] Re-run `se typogrify .` and  commit the change.

- [x] Re-run `se semanticate .` and commit the change.

- [x] Re-run `se modernize-spelling .` and commit the changes in an [Editorial] commit.

- [x] Remove `class="centered-text"`. We don't use custom classes that are used a couple of times. Clever CSS targeting can be used.

# preface.xhtml:

- [x] Remove `epub:type="se:letter.dateline"` from the footer. The text is not part of a letter.

# chapter-3.xhtml:

- [x] Lint is complaining about missing quotes, because there are no quotes in the following paragraphs after the salutation. Remove the quotes around the letter since it is already in a `<blockquote>`.

# chapter-4.xhtml:

- [x] The salutation goes inside the `<header>` element.

- [x] Lint is complaining about missing quotes, because there are no quotes in the following paragraphs after the salutation. I recommend removing the quotes around the letter since it is already in a `<blockquote>`.

# chapter-9.xhtml:

- [x] Replace
`<p epub:type="z3998:signature">(Signed) <abbr epub:type="z3998:given-name">J. H.</abbr> Jackson.</p>`
with
`<p>(Signed) <span epub:type="z3998:signature"><abbr epub:type="z3998:given-name">J. H.</abbr> Jackson</span>.</p>`

- [x] Since the headline is all in caps, you can simplify it as:
```
			<blockquote>
				<p>
					<b>“Murder of the Home Secretary,”<br/>
					“Suspect Arrested,”<br/>
					“Makes Full Confession.”</b>
				</p>
			</blockquote>
```

# chapter-16.xhtml:

- [x] In `<p>“I know. I will explain, but there’s no time now.</p>`, the page scans show an ending quote.

# chapter-17.xhtml:

- [x] Remove `The End`.

# local.css:

- [x] Replace:
```
.centered-text{
	text-align: center;
}
```
with the following CSS:
```
#chapter-1 blockquote,
#chapter-3 blockquote:first-of-type,
#chapter-9 blockquote:last-of-type{
	text-align: center;
}
```

# content.opf:

- [x] Since your LC subject headings have "Fiction" in them, it would be best to have a `Fiction` se:subject tag.

**Comment by huykirbyLL** [comment]
Hi Emma, thanks for reviewing my project. I just finished resolving all the issues. About your suggestion of removing quotation marks around letter blockquote, I also did that to letter blockquote in chapter 17 also to keep it consistent. Is that okay?

Also for communication, is it better to discuss my review issues in here or in my Google Group's thread?

Lam

**Comment by EmmaSweeney** [comment]
The changes look good!

You can discuss review issues here or on Google Groups. FWIW, I prefer discussing issues on GitHub, because it prevents me from getting repositories mixed up when reviewing multiple productions (I can't say the same for other editors). If you disagree with a change it may be best to discuss it on Google Groups, so other editors can comment on it.

**Comment by huykirbyLL** [comment]
I see, thank you Emma!

Lam
